# Generated by Django 5.2.12 on 2026-04-07 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='url_site',
            field=models.URLField(blank=True, null=True),
        ),
    ]
