# Generated by Django 5.2.12 on 2026-04-07 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_site_url_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='logo_type',
            field=models.CharField(blank=True, choices=[('', 'No Logo'), ('linkedin', 'LinkedIn'), ('github', 'GitHub'), ('twitter', 'Twitter'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('youtube', 'YouTube')], default='', max_length=20),
        ),
    ]
