# Generated by Django 5.2.12 on 2026-04-08 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_site_logo_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='scan_count',
            field=models.IntegerField(default=0),
        ),
    ]
