# Generated by Django 5.2.12 on 2026-04-09 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_site_session_key_site_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='style',
            field=models.CharField(choices=[('square', 'Square'), ('dots', 'Dots'), ('rounded', 'Rounded')], default='square', max_length=20),
        ),
    ]
