# Generated by Django 5.2.12 on 2026-04-09 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_scanlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanlog',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='app.site'),
        ),
    ]
