# Generated by Django 5.2.12 on 2026-04-09 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_scanlog_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanlog',
            name='is_unique',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scanlog',
            name='os',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
