# Generated by Django 5.2.12 on 2026-04-09 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_scanlog_is_unique_scanlog_os'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scanlog',
            name='is_unique',
        ),
    ]
