# Generated by Django 5.2.12 on 2026-04-11 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_site_center_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='font_type',
            field=models.CharField(choices=[('arial', 'Arial'), ('bold', 'Bold'), ('script', 'Script'), ('mono', 'Mono'), ('fancy', 'Fancy')], default='arial', max_length=20),
        ),
    ]
