# Generated by Django 5.2.12 on 2026-04-13 08:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_site_font_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='expire_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='expire_duration',
            field=models.CharField(choices=[('1m', '1 Minute'), ('10m', '10 Minutes'), ('1h', '1 Hour'), ('10h', '10 Hours'), ('1d', '1 Day'), ('7d', '7 Days'), ('30d', '30 Days'), ('forever', 'Forever')], default='forever', max_length=20),
        ),
    ]
