# Generated by Django 5.2.12 on 2026-04-14 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_site_created_at_site_expire_at_site_expire_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='style',
            field=models.CharField(choices=[('liquid', 'Liquid'), ('dots', 'Dots'), ('lines', 'Lines'), ('square', 'Square')], default='square', max_length=20),
        ),
    ]
