# Generated by Django 5.2.12 on 2026-04-14 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_site_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='style',
            field=models.CharField(choices=[('square', 'Square'), ('dots', 'Dots'), ('rounded', 'Rounded'), ('smooth', 'Smooth')], default='square', max_length=20),
        ),
    ]
