# Generated by Django 5.2.12 on 2026-04-14 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_site_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='background_color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
    ]
